#ifndef ERROR_CODE_H
#define ERROR_CODE_H

/*
	错误代码定义头文件
	关键词：err code，错误代码
*/

typedef enum
{
	SUCCESS,  //0 
	ERR_USR_XML_PARSER,  //1     
	ERR_USR_PARSE_REQ, //2
	ERR_USR_PRE_PROC, //3
	ERR_USR_UNKNOW_MSG_TYPE, //4
	ERR_USR_PACKET_ILLEGAL, //5
	ERR_PULSE_NORMAL,//6
	ERR_REMOTE_PROC_RECV, //7
	ERR_REMOTE_PROC_SEND, //8
	ERR_PROC_LANGUAGE, //9
	ERR_PROC_TXT_FROMAT, //10
	ERR_TRANS_STOP_NO_DOMAIN, //11
	ERR_TRANS_STOP_NO_TEXT, //12
	ERR_ILLEGAL_MSG, //13
	ERR_PACKET_MSG, //14
	ERR_CREATE_OLT_TRANSACTION, //15
	ERR_DB_EXCEPTION, //16
	ERR_ILLEGAL_INPUT, //17
	ERR_ILLEGAL_DOMAIN, //18
	ERR_USR_RTT_SENT_TOO_LONG, //19
	ERR_INTER_STATE, //20
	ERR_DOMAIN_NO_ALIVE, //领域暂不可用 //21
	ERR_OPEN_TRANS_FILE_FAILED, //22
	ERR_UNSUPORT_FILE, //23
	ERR_DB_FAILED, //24
	ERR_DB_NORESULT, //25
	ERR_OPEN_RESULT_FILE_FAILED, //26
	ERR_DICT_NOT_FIND_IN_INFOMAP, //27
	ERR_DICT_NOT_FIND_IN_USRMAP, //28
	ERR_NEW_DICTIONARY, //29
	ERR_DICT_NOT_FIND_IN_USRDICT, //30
	ERR_DICTGROUP_NOT_FIND_IN_USRDICT, //31
	ERR_DICT_NOT_FIND, //32
	ERR_DICTWORD_INSERT_SAME_WORD, //33
	ERR_DICTWORD_NOT_FIND_WORD_ID, //34
	ERR_DICTWORD_NOT_FIND_WORD_BY_WORD_ID, //35
	ERR_DICTWORD_NOT_FIND_WORD_BY_WORD_ID_IN_VEC, //36
	ERR_DB_WORD_VEC_NOT_RIGHT, //37
	ERR_DICT_LOAD_WORD_FILE_FAILED, //38
	ERR_WORD_MODIFY_SAMEWORD_WITH_SRC_OR_TGT, //39
	ERR_DICT_MODIFY_SAME_DICTID,//40
	ERR_CALL_DOC_EXTRACT_RPC_FAILED, //41
	ERR_SAVE_DOC_POS_FILE_FAIELD, //42
	ERR_EXTRACT_FILE_IS_NULL, //43
	ERR_OPEN_DOC_POS_FILE_FAILED, //44
	ERR_CALL_DOC_RESTORE_RPC_FAILED, //45
    ERR_DB_TEMPLATE_VEC_NOT_RIGHT,//46
	ERR_TEMPLATE_INSERT_SAME, //47
	ERR_TEMPLATE_FORMATE_ERROR,//48
	ERR_TEMPLATE_INSERT_SAME_ID, //49
	ERR_TEMPLATE_NOT_FIND_TEMPLATE_ID, //50
	ERR_TEMPALTE_MODIFY_SAME, //51
	ERR_TEMPLATELIB_NOT_FIND_IN_INFOMAP, //52
	ERR_TEMPLATELIB_NOT_FIND_IN_USRMAP, //53
	ERR_NEW_TEMPLATELIB, //54
	ERR_TEMPLATELIBGROUP_NOT_FIND_IN_USRTEMPLATELIB, //55
	ERR_TEMPLATELIB_LOAD_TEMPLATE_FILE_FAILED, //56
	ERR_TEMPLATELIB_NOT_FIND, //57
	ERR_TEMPLATELIB_MODIFY_SAME_TEMPLATELIBID, //58
	ERR_TEMPLATELIB_NOT_FIND_IN_USRTEMPLATELIB, //59
	ERR_SAVE_BASE_POS_FILE_FAIELD, //60
	ERR_SAVE_BASE_SOURCE_FILE_FAILED, //61
	ERR_READ_TXT_INPUT_FILE_FAILED, //62
	ERR_READ_DOC_INPUT_FILE_FAILED, //63
	ERR_SAVE_DOC_SOURCE_FILE, //64
	ERR_READ_HTML_INPUT_FILE_FAILED, //65
	ERR_WRITE_HTML_SOURCE_FILE, //66
	ERR_READ_HTML_EXT_FILE_FAILED, //67
	ERR_GET_TGT_VEC_FROM_DB, //68
	ERR_OPEN_DOC_SOURCE_FILE_FAILED, //69
	ERR_SAVE_DOC_POS_FILE, //70
	ERR_READ_BASE_SOURCE_FILE, //71
	ERR_READ_BASE_POS_FILE, //72
	ERR_PARSE_RESULT_FORMAT, //73
	ERR_WRITE_BASE_RESULT_FILE,//74
	ERR_READ_PDF_INPUT_FILE_FAILED, //75
	ERR_WRITE_PDF_SOURCE_FILE, //76
	ERR_READ_PDF_EXT_FILE_FAILED, //77

	ERR_USR_ILLEGAL_CONTROL_TYPE, //78
	ERR_NO_NEED_TRANS, //79
	ERR_TRANS_CONTROL_NOT_THIS_USR, //80
	ERR_NOT_FIND_TEXT, //81
	ERR_TRANS_CONTROL_DOMAIN_NOT_FIND, //82
	ERR_TRANS_CONTROL_USR_CANCEL, //83
	ERR_USR_POST_PROC, //84

	ERR_CHSEG_INSERT, //85
	ERR_CHSEG_DELETE, //86
	ERR_CHSEG_MODIFY, //87
	ERR_CHSEG_LOAD, //88
	ERR_CHSEG_RECOVERY, //89

	ERR_NODICT_GET, //90
	ERR_NOTEMPLATELIB_GET, //91
	ERR_NOWORD_GET, //92
	ERR_NOTEMPLATE_GET, //93
    
    ERR_PERMISSION_TIME, //94
    ERR_PERMISSION_CHARACTER, //95
	ERR_READ_WORD_INPUT_FILE_FAILED, //96
	ERR_READ_WORD_EXT_FILE_FAILED, //97
	ERR_PARSE_WORD_XML, //98
	ERR_CREATE_WORD_RESULT_XML, //99
	ERR_SAVE_WORD_RECOVER_XML, //100

	ERROR_UNDEFINE, //101 暂未定义
	ERR_UNKNOW 

} ErrorCode;



#endif //ERROR_CODE_H
