#include "MsgType.h"

const string MSG_TYPE_ECHO("Echo");
const string MSG_TYPE_PULSE("TransPulse");
const string MSG_TYPE_TRANSLATE("Translate");
const string MSG_TYPE_RTT_TRANS("RealTimeTrans");
const string MSG_TYPE_RTT_SEG("RealTimeSeg");
const string MSG_TYPE_OLT_TRANS("OffLineTrans");
const string MSG_TYPE_DEL_TASK("TaskDelete");
const string MSG_TYPE_QUE_TASK("TaskQuery");
const string MSG_TYPE_REORDER_TASK("TaskReorder");
const string MSG_TYPE_DICT_CREATE("DictCreate");
const string MSG_TYPE_DICT_DELETE("DictDelete");
const string MSG_TYPE_DICT_MODIFY("DictModify");
const string MSG_TYPE_SYS_DICT_INSERT("InsertSysDict");//
const string MSG_TYPE_DICT_RECOVER("DictRecover");
const string MSG_TYPE_DICT_WORDS_RECOVER("WordRecover");
const string MSG_TYPE_TEMPLATELIB_CREATE("TemplateLibCreate");
const string MSG_TYPE_TEMPLATELIB_DELETE("TemplateLibDelete");
const string MSG_TYPE_TEMPLATELIB_MODIFY("TemplateLibModify");
const string MSG_TYPE_WORD_INSERT("WordInsert");
const string MSG_TYPE_WORD_DELETE("WordDelete");
const string MSG_TYPE_WORD_MODIFY("WordModify");
const string MSG_TYPE_WORD_DOWNLOAD("WordDownload");
const string MSG_TYPE_WORD_LOAD("WordLoad");
const string MSG_TYPE_TEMPLATE_INSERT("TemplateInsert");
const string MSG_TYPE_TEMPLATE_DELETE("TemplateDelete");
const string MSG_TYPE_TEMPLATE_MODIFY("TemplateModify");
const string MSG_TYPE_TEMPLATE_LOAD("TemplateLoad");
const string MSG_TYPE_TEMPLAGE_CREATE_LIB("TemplateCreateLib");
const string MSG_TYPE_TEMPLAGE_DELETE_LIB("TemplateDeleteLib");
const string MSG_TYPE_SYS_TEMPLATELIB_INSERT("InsertSysTemplateLib");//
const string MSG_TYPE_TEMPLATE_RECOVER("TemplateRecover");//
const string MSG_TYPE_TEMPLATELIB_RECOVER("TemplateLibRecover");//
const string MSG_TYPE_TEMPLAGE_INSERT("TemplateInsert");
const string MSG_TYPE_TEMPLAGE_DEL_ENTRY("TemplateDelEntry");
const string MSG_TYPE_TEXT_PROCESS("TextProcess");
const string MSG_TYPE_TRANS_STOP("TransStop");
const string MSG_TYPE_DICT_IMPORT("DictImport");
const string MSG_TYPE_OLT_DOWNLOAD("OltDownload");
const string MSG_TYPE_OLT_CONTROL("OltControl");
const string MSG_TYPE_OLT_SENT("OltSent");
const string MSG_TYPE_CHSEG_WORD_INSERT("ChSegWordInsert");
const string MSG_TYPE_CHSEG_WORD_DELETE("ChSegWordDelete");
const string MSG_TYPE_CHSEG_WORD_MODIFY("ChSegWordModify");
const string MSG_TYPE_CHSEG_WORD_LOAD("ChSegWordLoad");
const string MSG_TYPE_CHSEG_WORD_RECOVERY("ChSegWordRecovery");
///////////////////
const string MSG_TYPE_AFTER_DICT_CREATE("AfterDictCreate");
const string MSG_TYPE_AFTER_DICT_DELETE("AfterDictDelete");
const string MSG_TYPE_AFTER_DICT_MODIFY("AfterDictModify");
const string MSG_TYPE_AFTER_WORD_INSERT("AfterWordInsert");
const string MSG_TYPE_AFTER_WORD_DELETE("AfterWordDelete");
const string MSG_TYPE_AFTER_WORD_MODIFY("AfterWordModify");
const string MSG_TYPE_AFTER_WORD_LOAD("AfterWordLoad");
const string MSG_TYPE_AFTER_DICT_RECOVER("AfterDictRecover");
const string MSG_TYPE_AFTER_DICT_WORDS_RECOVER("AfterWordRecover");
